# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Mem/Mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Mem || ORIG_REF_NAME==Mem} -quiet] -quiet

# XDC: ip/Mem/Mem_ooc.xdc
